# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false
    etag:                   true
    cache:                  true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false
    logging_enabled:        true

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    standard_helpers: [Partial, Cache, I18N, Date, Number]
    # Form security secret (CSRF protection)
    csrf_secret:            67e18eed7e63a92229b7d1c5fa8327b5d867e696

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    
    # Disable GZIP, web server will do it (and for JS+CSS).
    compressed: false
    
    # Language manager
    i18n: true
    default_culture: fr_FR