# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        ZenTracker CMS
    #description:  symfony project
    #keywords:     symfony, project
    #language:     fr
    #robots:       index, follow
    X-UA-Compatible:   chrome=1
    

  stylesheets:    []
  
  javascripts:
    - http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js
    - /js/redactor/redactor.js
    - http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js
    - /js/bootstrap.js
    - /js/jquery.paginate.js
    - /js/zt_interface.js
    - /js/zt_render.js

  has_layout:     true
  layout:         layout