# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

all:
  is_secure: true

delete:
  credentials: [[adm, mod]]

edittopic:
  credentials: [[adm, mod]]

add:
  credentials: adm

addfrm:
  credentials: adm